### ISSUE TITLE
Does not create folder on first run.

### ISSUE THREAD

**Issue by AustinYQM** [MemeDistributionCo/ComBot#35]
```
PS D:\Discord Bot> java -jar "D:\Discord Bot\ComBotLauncher.jar"
Found config file, loading

====================
MOTD: Message of the Day: Thank you for using ComBot! The newest version is v1.3.3! This version makes the 'plugin' command more simple, and increases the usefulness of the 'plinfo' command. The previous version, v1.3.2, added usage statistics. If there's a problem, please join the discord here and tell me about it: https://discord.gg/kgpguGh
====================
You seem to be missing
check-update and auto-download-update
in your conifg file. I'll set those to true for now, but be sure to add them to your file later.
Check for update: true
Auto-download: true

Using current version
Starting bot...ComBot.v1.3.3.jar
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
        at org.json.JSONTokener.syntaxError(JSONTokener.java:451)
        at org.json.JSONObject.<init>(JSONObject.java:195)
        at org.json.JSONObject.<init>(JSONObject.java:319)
        at com.mdc.combot.permissions.DefaultPermissionManager.readPermissionsFile(DefaultPermissionManager.java:208)
        at com.mdc.combot.permissions.DefaultPermissionManager.getPermissionManager(DefaultPermissionManager.java:220)
        at com.mdc.combot.ComBot.<init>(ComBot.java:99)
        at com.mdc.combot.BotLauncher.startBot(BotLauncher.java:81)
        at com.mdc.combot.BotLauncher.main(BotLauncher.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at com.mdc.combot.launcher.ComBotLauncher.loadComBot(ComBotLauncher.java:160)
        at com.mdc.combot.launcher.ComBotLauncher.main(ComBotLauncher.java:114)
Aug 10, 2020 12:03:16 PM com.mdc.combot.BotLauncher startBot
INFO: Starting...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
javax.security.auth.login.LoginException: The provided token is invalid!
        at net.dv8tion.jda.core.entities.impl.JDAImpl.verifyToken(JDAImpl.java:276)
        at net.dv8tion.jda.core.entities.impl.JDAImpl.verifyToken(JDAImpl.java:214)
        at net.dv8tion.jda.core.entities.impl.JDAImpl.login(JDAImpl.java:161)
        at net.dv8tion.jda.core.JDABuilder.buildAsync(JDABuilder.java:662)
        at net.dv8tion.jda.core.JDABuilder.buildBlocking(JDABuilder.java:701)
        at net.dv8tion.jda.core.JDABuilder.buildBlocking(JDABuilder.java:730)
        at com.mdc.combot.ComBot.login(ComBot.java:663)
        at com.mdc.combot.ComBot.start(ComBot.java:425)
        at com.mdc.combot.BotLauncher.startBot(BotLauncher.java:84)
        at com.mdc.combot.BotLauncher.main(BotLauncher.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at com.mdc.combot.launcher.ComBotLauncher.loadComBot(ComBotLauncher.java:160)
        at com.mdc.combot.launcher.ComBotLauncher.main(ComBotLauncher.java:114)
Aug 10, 2020 12:03:17 PM com.mdc.combot.BotLauncher startBot
SEVERE: Unable to log in! Yikes! (Invalid token?) The provided token is invalid!
```

**Comment by xDestx** [comment]
Apologies for the late reply. Though this project can easily be considered dead, this is something I want to change if I ever get around to it. The bot creates the folders in your **home directory**, which is most likely something like `C:\Users\yourusername\ComBot`. All of the config files should generate there. 

The change I have in mind will create the files in the current working directory. (Whatever pwd would show) I actually have this listed as a future change right here #34
